// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOUuFi2x4i1BCpZe-vXRFuWLKrhuKpZKo',
    appId: '1:652195937327:web:f3b50d707087b18ac85ada',
    messagingSenderId: '652195937327',
    projectId: 'gymapp-38904',
    authDomain: 'gymapp-38904.firebaseapp.com',
    storageBucket: 'gymapp-38904.appspot.com',
    measurementId: 'G-GP4D8ZM8SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-Vu9cDN4x3ROD8uVS60R612AT8mLLTw',
    appId: '1:652195937327:android:32275779e8cc5a06c85ada',
    messagingSenderId: '652195937327',
    projectId: 'gymapp-38904',
    storageBucket: 'gymapp-38904.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3ihzsuOrcYHQfFy4_xerzY58fAAeSEc',
    appId: '1:652195937327:ios:017ced824e68440cc85ada',
    messagingSenderId: '652195937327',
    projectId: 'gymapp-38904',
    storageBucket: 'gymapp-38904.appspot.com',
    iosBundleId: 'com.example.gymApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3ihzsuOrcYHQfFy4_xerzY58fAAeSEc',
    appId: '1:652195937327:ios:017ced824e68440cc85ada',
    messagingSenderId: '652195937327',
    projectId: 'gymapp-38904',
    storageBucket: 'gymapp-38904.appspot.com',
    iosBundleId: 'com.example.gymApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOUuFi2x4i1BCpZe-vXRFuWLKrhuKpZKo',
    appId: '1:652195937327:web:3fee9d780ca2487dc85ada',
    messagingSenderId: '652195937327',
    projectId: 'gymapp-38904',
    authDomain: 'gymapp-38904.firebaseapp.com',
    storageBucket: 'gymapp-38904.appspot.com',
    measurementId: 'G-LT3LNL1CZ2',
  );
}
